# Generated by Django 5.2.8 on 2025-12-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_scanlog_country_scanlog_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelistdomain',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
