# Generated by Django 5.2.17 on 2026-09-10 19:57

import django.db.models.functions.text
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Length, Lower


def _preferred_rank(entries):
    positive_ranks = [entry.rank for entry in entries if entry.rank > 0]
    return min(positive_ranks) if positive_ranks else 0


def canonicalize_existing_domains(apps, schema_editor):
    whitelist_domain = apps.get_model("api", "WhitelistDomain")

    duplicate_groups = (
        whitelist_domain.objects.annotate(canonical=Lower("domain"))
        .values("canonical")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for group in duplicate_groups.iterator(chunk_size=1000):
        entries = list(
            whitelist_domain.objects.filter(domain__iexact=group["canonical"])
            .only("id", "domain", "rank")
            .order_by("rank", "id")
        )
        winner = entries[0]
        winner.rank = _preferred_rank(entries)
        whitelist_domain.objects.filter(
            id__in=[entry.id for entry in entries[1:]]
        ).delete()
        whitelist_domain.objects.filter(id=winner.id).update(
            domain=group["canonical"],
            rank=winner.rank,
        )

    whitelist_domain.objects.update(domain=Lower("domain"))

    trailing_dot_entries = whitelist_domain.objects.filter(
        domain__endswith="."
    ).iterator(chunk_size=1000)
    for entry in trailing_dot_entries:
        canonical = entry.domain.rstrip(".")
        if not canonical or len(canonical) > 253:
            raise RuntimeError(
                f"Cannot safely canonicalize whitelist domain ID {entry.id}"
            )
        existing = whitelist_domain.objects.filter(domain=canonical).first()
        if existing is None:
            whitelist_domain.objects.filter(id=entry.id).update(domain=canonical)
            continue

        existing.rank = _preferred_rank([existing, entry])
        whitelist_domain.objects.filter(id=existing.id).update(rank=existing.rank)
        whitelist_domain.objects.filter(id=entry.id).delete()

    if whitelist_domain.objects.annotate(domain_length=Length("domain")).filter(
        domain_length__gt=253
    ).exists():
        raise RuntimeError("A whitelist domain exceeds the DNS hostname limit")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_whitelistauditevent'),
    ]

    operations = [
        migrations.RunPython(canonicalize_existing_domains, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='whitelistdomain',
            name='domain',
            field=models.CharField(db_index=True, max_length=253, unique=True),
        ),
        migrations.AddConstraint(
            model_name='whitelistdomain',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('domain'), name='whitelist_domain_case_insensitive_unique'),
        ),
    ]
